spring:    
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: welcome
    driverClassName: com.mysql.cj.jdbc.Driver


         

       
server:
  port: 8080

      
      